name: Deploy to Cloudflare Pages

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build
        env:
          CF_PAGES: 1
          PUBLIC_SUPABASE_URL: ${{ secrets.PUBLIC_SUPABASE_URL }}
          PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SIGNED_URL_JWT_SECRET: ${{ secrets.SIGNED_URL_JWT_SECRET }}
          EMAIL_STRATEGY: ${{ env.EMAIL_STRATEGY }}
          PLUNK_SECRET_API_KEY: ${{ secrets.PLUNK_SECRET_API_KEY }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: .svelte-kit

  publish:
    permissions:
      contents: read
      deployments: write
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1.5.0
        with:
          # Cloudflare API Token
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          # Cloudflare Account ID
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # The name of the Pages project to upload to
          projectName: as-built
          # The directory of static assets to upload
          directory: .svelte-kit/cloudflare
