name: Deploy to Cloudflare Pages

on:
  push:
  pull_request:

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - uses: actions/setup-node@v3
        with:
          node-version: 18
        
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build
        env:
          CF_PAGES: 1
  publish:
    timeout-minutes: 60
    permissions:
      contents: read
      deployments: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1.5.0
        with:
          # Cloudflare API Token
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          # Cloudflare Account ID
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # The name of the Pages project to upload to
          projectName: as-built
          # The directory of static assets to upload
          directory: .svelte-kit/cloudflare
